# Site settings
title: German Quest
subtitle: 
email: gutentag [at] german.quest
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: German Quest
street_address: somewhere in
city: 
state: 
zip_code: (vielleicht)
country: Germany
phone: 

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
